sudo: required
services:
- docker
jobs:
  include:
    - stage: docker
      before_install:
      - openssl aes-256-cbc -K $encrypted_d9216dbb936d_key -iv $encrypted_d9216dbb936d_iv
        -in travis_gcloud_auth.json.enc
        -out travis_gcloud_auth.json
        -d
      - docker login -u _json_key -p "$(cat travis_gcloud_auth.json)" https://gcr.io
      - docker pull gcr.io/rasa-platform/platform-demo:latest || true
      script:
      - cd moodbot && docker build
        -t gcr.io/rasa-platform/platform-demo:v$TRAVIS_BUILD_NUMBER
        -t gcr.io/rasa-platform/platform-demo:latest
        --cache-from gcr.io/rasa-platform/platform-demo:latest
        .
      after_success:
      - docker push gcr.io/rasa-platform/platform-demo:latest
      - docker push gcr.io/rasa-platform/platform-demo:v$TRAVIS_BUILD_NUMBER
