sudo: required
services:
- docker
jobs:
  include:
    - stage: docker
      before_install:
      - openssl aes-256-cbc -K $encrypted_d9216dbb936d_key -iv $encrypted_d9216dbb936d_iv
        -in secrets.tar.enc
        -out secrets.tar
        -d
      - tar xvf secrets.tar
      - mv .env moodbot
      - docker login -u _json_key -p "$(cat travis_gcloud_auth.json)" https://gcr.io
      - docker pull gcr.io/rasa-platform/platform-demo:latest || true
      script:
      - cd moodbot && docker build
        -t gcr.io/rasa-platform/platform-demo:v$TRAVIS_BUILD_NUMBER
        -t gcr.io/rasa-platform/platform-demo:latest
        --build-arg RASA_PYPI_PASSWORD=$RASA_PYPI_PASSWORD
        --build-arg RASA_PYPI_USER=$RASA_PYPI_USER
        --cache-from gcr.io/rasa-platform/platform-demo:latest
        .
      after_success:
      - docker push gcr.io/rasa-platform/platform-demo:latest
      - docker push gcr.io/rasa-platform/platform-demo:v$TRAVIS_BUILD_NUMBER
env:
  global:
  - secure: kuvQPuuPLVySig3/IQQU1W7EsZWiOuvzytfItigino+fCcYShRpYJp79XQ7JwttdUIEemuc6OAyUm5whpoMcbP0Of7ulOsJS7AozVcfyQTtjqB5fAhyIhQK19DTIE21siq0hiw/s+/vzd8gbg99mlr3Z7jtxQ0c8rnyOjvdcyvpMgIZkIIDdb36uHJ5AmqAgldWwf8BIyIz19a0aDau0YmIoxjJgSBV8o7519I9AvctA1t2Dh+P58VTIh8q8n0kTmAPwmMkhYqatX2Ab2fT5gpuF2TCRQLXfJpb6UXppxNo1aNo5KEmNJlTW2uyUGliShaa16SCm2RWaJMXNYTFVWesno3T2AquVcMkhax18JvACqxoYXaSsydCruxnTkvVdT3QW1x5YaogTHXrFoceHSVJsWMLzMYYuOgtHEZv3KodJX6FfKvupWTURPBm2EHUDpHsbf5RA4u8d0096lBB8jEcWI1jrH87g8BUU+OelRHEKqkKERLyZEyKj//eJXBC597WTYaF/GobvK+gl5i2jrH2kGGD8kRiVkYFHvfyDounH3OMrAOUZbNiUt9jpFQmh0PL2ZqgPqhZk2wSQyMlAf8EhNiBUYOCsv321oFfh3aN7+B6+B8OeSdIV6yjppGryeej+wj4Z4OU7fvluLlGQSJxaTAKGB6mGkiInR9NF3Dk=
  - secure: 13/cjvIZeN1dVgcR3LrAzMi1jiHnW4WTxZ7VJJuzd2uc1lOWmdpZnwNaJ+e3N/L5lXVBCBYVf1LxC9Xc8jMfLDSKYacgtAk67k52QJmjHAZfKo+8ASLWokUI6wJs4NWAg2kgncYocl8EmQyGs8GT3sds1jsULYzYOjABfYWPXt8Gk+erdzh/8nC0YIbCz0ftlqsxc4qXk7Xsr13/qr7/GYab3LTdtuz2ewLhY8KifvWMXVPIJQtsFgq651OE7Rrcu3MIsva2HG1ZjM7qbk6Lyldr98wN1K5kw2NFJ++jx+0Dhh8p5IzLLio5UjiM/Jh8yILcy7ikGsqItQBsDrl5yAF8KGD3fXkZby3G2es7Z9JtuTmlmVPPhfSFwE5IdoPyNVBMmxnxqEP93vl3s1XsB4V3piCw/7cHNVOKvy8AhtLNRnH/TDT3LBZbiiXAEGO7mWRv4fEjVIFA+Fd04JglpXuqNTi/HEvgmOu83wCcpeadqkj392QRs8/bdsayxM36DDVob6WM5DQzZJBUpUNJzgkat5uOwy34rCr/707sLkdhFlmFpBVuEztI7u6kOKOMxe8XvXXqxc4L09xxNGDQxaJ/8t4/CFJF8erBPixE/US8M6XQHU77hVqVsi/FNGjDnRFE3Egch7Q8YWNIVFVzcq40ZCZ6ncJ5tjDSK4Gf5Pk=
