version: '3'
services:
  app:
    image: "gcr.io/rasa-platform/platform-demo:${RASA_PLATFORM_VERSION:-latest}"
    container_name: "app"
    environment:
      RASA_REMOTE_CORE_ENDPOINT_URL: "http://core"
      RASA_CORE_TOKEN: $RASA_CORE_TOKEN
      RASA_API_ENDPOINT_URL: "http://api-nlu"
    expose:
    - "5001"
    depends_on:
    - core
    volumes:
    - ./moodbot/models/dialogue:/app/models/dialogue

  nlu:
    image: "gcr.io/rasa-platform/enterprise-nlu:${RASA_PLATFORM_VERSION:-latest}"
    container_name: "nlu"
    expose:
    - "80"
    volumes:
    - ./nlu-projects:/app/projects
    environment:
      RASA_PORT: "80"
      RASA_DUCKLING_HTTP_URL: "http://duckling"
      RASA_TOKEN: ${RASA_NLU_TOKEN}
      MONGO_HOST: "mongodb://mongo"
      MONGO_PORT: "27017"
      MONGO_DB: "nlu-backend"

  core:
    image: "gcr.io/rasa-platform/enterprise-core:${RASA_PLATFORM_VERSION:-latest}"
    container_name: "core"
    expose:
    - "80"
    volumes:
    - ./core-model:/app/model
    environment:
      RASA_CORE_REMOTE_PORT: "80"
      RASA_CORE_MODEL_DIR: "/app/model"
      RASA_CORE_TOKEN: ${RASA_CORE_TOKEN}
      MONGO_HOST: "mongodb://mongo"
      MONGO_PORT: "27017"
      MONGO_DB: "nlu-backend"
      RASA_NLU_HOST: "http://nlu"
      RASA_NLU_TOKEN: ${RASA_NLU_TOKEN}
      RASA_PLATFORM_HOST: "http://api-nlu"

  api-core:
    image: "gcr.io/rasa-platform/api-core:${RASA_PLATFORM_VERSION:-latest}"
    container_name: "api-core"
    expose:
    - "80"
    environment:
      SELF_PORT: "80"
      MONGO_HOST: "mongodb://mongo"
      MONGO_PORT: "27017"
      MONGO_DB: "nlu-backend"
      RASA_NLU_HOST: "http://nlu"
      RASA_NLU_TOKEN: ${RASA_NLU_TOKEN}
      RASA_CORE_HOST: "http://core"
      RASA_CORE_TOKEN: ${RASA_CORE_TOKEN}
      RASA_PLATFORM_HOST: "http://api-nlu"

  api-nlu:
    image: "gcr.io/rasa-platform/api-nlu:${RASA_PLATFORM_VERSION:-latest}"
    container_name: "api-nlu"
    expose:
    - "80"
    environment:
      SELF_PORT: "80"
      RASA_CORE_MODEL_DIR: "/app/model"
      MONGO_HOST: "mongodb://mongo"
      MONGO_PORT: "27017"
      MONGO_DB: "nlu-backend"
      RASA_NLU_HOST: "http://nlu"
      RASA_NLU_TOKEN: ${RASA_NLU_TOKEN}
      PASSWORD_SALT: ${PASSWORD_SALT}
      TOKEN_SALT: ${TOKEN_SALT}

  chat-ui:
    image: "gcr.io/rasa-platform/chat-ui:${RASA_PLATFORM_VERSION:-latest}"
    container_name: "chat-ui"
    expose:
    - "80"

  platform-ui:
    image: "gcr.io/rasa-platform/platform-ui:${RASA_PLATFORM_VERSION:-latest}"
    container_name: "platform-ui"
    expose:
    - "80"

  mongo:
    image: "mongo:3.7-jessie"
    container_name: "mongo"
    expose:
    - "27017"
    volumes:
    - ./mongo:/data/db

  duckling:
    image: "rasa/duckling:latest"
    container_name: "duckling"
    expose:
    - "8000"

  nginx:
    image: "gcr.io/rasa-platform/nginx:${RASA_PLATFORM_VERSION:-latest}"
    container_name: "nginx"
    ports:
    - "80:80"
    - "443:443"
    depends_on:
    - nlu
    - core
    - api-core
    - api-nlu
    - chat-ui
    - platform-ui
