version: '3'
services:
  app:
    build:
      context: moodbot
      dockerfile: Dockerfile
      args:
        RASA_PYPI_USER: ${RASA_PYPI_USER}
        RASA_PYPI_PASSWORD: ${RASA_PYPI_PASSWORD}

    container_name: "app"
    environment:
      SELF_PORT: "5001"
      RASA_REMOTE_CORE_ENDPOINT_URL: "http://core"
      RASA_CORE_TOKEN: $RASA_CORE_TOKEN
      RASA_API_ENDPOINT_URL: "http://api-nlu"
    expose:
    - "5001"

  nlu:
    image: "gcr.io/rasa-platform/enterprise-nlu:latest"
    container_name: "nlu"
    expose:
    - "80"
    volumes:
    - ./moodbot/models/nlu/current:/app/projects/default/current
    environment:
      RASA_PORT: "80"
      RASA_DUCKLING_HTTP_URL: "http://duckling"
      MONGO_HOST: "mongodb://mongo"
      MONGO_PORT: "27017"
      MONGO_DB: "nlu-backend"
      RASA_TOKEN: ${RASA_NLU_TOKEN}

  core:
    image: "gcr.io/rasa-platform/enterprise-core:latest"
    container_name: "core"
    expose:
    - "80"
    volumes:
    - .:/app
    environment:
      RASA_CORE_REMOTE_PORT: "80"
      RASA_CORE_MODEL_DIR: "/app/model"
      MONGO_HOST: "mongodb://mongo"
      MONGO_PORT: "27017"
      MONGO_DB: "nlu-backend"
      RASA_NLU_HOST: "http://nlu"
      RASA_PLATFORM_HOST: "http://api-nlu"
      RASA_CORE_MODEL_DIR: "/app/model"
      RASA_NLU_TOKEN: ${RASA_NLU_TOKEN}
      RASA_CORE_TOKEN: ${RASA_CORE_TOKEN}
    volumes:
    - ./moodbot/models/dialogue:/app/model

  api-core:
    image: "gcr.io/rasa-platform/api-core:latest"
    container_name: "api-core"
    expose:
    - "80"
    volumes:
    - .:/app
    environment:
      SELF_PORT: "80"
      RASA_CORE_MODEL_DIR: "/app/model"
      MONGO_HOST: "mongodb://mongo"
      MONGO_PORT: "27017"
      MONGO_DB: "nlu-backend"
      RASA_NLU_HOST: "http://nlu"
      RASA_PLATFORM_HOST: "http://api-nlu"
      RASA_CORE_MODEL_DIR: "/app/model"
      RASA_NLU_TOKEN: ${RASA_NLU_TOKEN}
      RASA_CORE_TOKEN: ${RASA_CORE_TOKEN}
    volumes:
    - ./moodbot/models/dialogue:/app/model

  api-nlu:
    image: "gcr.io/rasa-platform/api-nlu:latest"
    container_name: "api-nlu"
    expose:
    - "80"
    environment:
      SELF_PORT: "80"
      RASA_CORE_MODEL_DIR: "/app/model"
      MONGO_HOST: "mongodb://mongo"
      MONGO_PORT: "27017"
      MONGO_DB: "nlu-backend"
      RASA_NLU_HOST: "http://nlu"
      RASA_NLU_TOKEN: ${RASA_NLU_TOKEN}
      PASSWORD_SALT: ${PASSWORD_SALT}
      TOKEN_SALT: ${TOKEN_SALT}

    volumes:
    - ./moodbot/models/nlu/current:/app/projects/default/current

  chat-ui:
    image: "gcr.io/rasa-platform/chat-ui:latest"
    container_name: "chat-ui"
    expose:
    - "80"

  platform-ui:
    image: "gcr.io/rasa-platform/platform-ui:latest"
    container_name: "platform-ui"
    expose:
    - "80"

  mongo:
    image: "mongo:latest"
    container_name: "mongo"
    expose:
    - "27017"
    volumes:
    - ./mongo:/data/db

  duckling:
    image: "rasa/duckling:latest"
    container_name: "duckling"
    expose:
    - "8000"

  nginx:
    image: "nginx:latest"
    container_name: "nginx"
    volumes:
    - ../platform-deployment/nginx.conf:/etc/nginx/conf.d/default.conf
    ports:
    - "80:80"
    - "443:443"
    depends_on:
    - nlu
    - core
    - api-core
    - api-nlu
    - chat-ui
    - platform-ui
